server:
  port: 8080

#spring.mvc.throw-exception-if-no-handler-found=true
#spring.resources.add-mappings=false
spring:
  mvc:
    throw-exception-if-no-handler-found: true  #遇到404错误时抛出异常，不重定向到/error
  thymeleaf:
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  resources:
    add-mappings: false
  mysql:
    druid:
      url: jdbc:mysql://120.77.44.207:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: '@Linhuanzhen123'
      type: com.alibaba.druid.pool.DruidDataSource
      dbType: mysql
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    mybatis:
      # mapper 扫描路径
      mapperLocations: classpath*:com/springboot/starter/dao/mapper/*Dao.xml
      # 是否开启xml热加载
      enabled: true

security:
  basic:
    enabled: false


# jwt
authorization:
  config:
    jwt:
      header: Authorization
      secret: '@iloveyou'
      expiration: 3600  #秒
      tokenHead: Bearer
    route:
      login: auth/login
      logout: auth/logout
      refresh: auth/refresh
      register: auth/register

api: test